version: "2"
services:
   chicv:
    build:  .
    extra_hosts:
     - "sw.app:127.0.0.1"
     - "jfn.app:127.0.0.1"
    ports:
     - "3101:80"
     - "3306:3306"
     - "9203:9200"
    volumes:
      - "/Users/shiyy/Work/stylewe:/home/chicv/Code"
    mem_limit: "2g"
    memswap_limit: 2g
    privileged: true
    tty: true
    cpu_shares: 73
    cpuset: 0,1
    container_name: chicv-web
    dns: 8.8.8.8
    ulimits:
     nproc: 65535
     nofile:
      soft: 20000
      hard: 40000
